# Generated by Django 4.2.1 on 2023-08-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
