# Generated by Django 4.2.1 on 2023-08-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_gameroom_options_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attempt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
