# Generated by Django 4.1 on 2023-08-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_player_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_set', to='room.gameroom'),
        ),
    ]
