# Generated by Django 4.1 on 2023-11-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_player_isguest_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
