# Generated by Django 4.1 on 2023-09-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Problems',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Placeholder for user.', max_length=50, unique=True)),
                ('value', models.CharField(help_text='Fixed parameter value that is required for library.', max_length=50, unique=True)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Tenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Placeholder for user.', max_length=50, unique=True)),
                ('value', models.CharField(help_text='Fixed parameter value that is required for library.', max_length=50, unique=True)),
                ('points', models.PositiveIntegerField(default=10)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tenses',
            },
        ),
        migrations.CreateModel(
            name='Verbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Fixed parameter value that is required for library.', max_length=50)),
                ('isRegular', models.BooleanField()),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Verbs',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctAnswer', models.CharField(help_text='Correct answer.', max_length=50)),
                ('answer', models.CharField(help_text='Your answer.', max_length=50)),
                ('isCorrect', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects')),
                ('tense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenses')),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
