# Generated by Django 4.2.1 on 2023-08-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjects',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='tenses',
            options={'verbose_name_plural': 'Tenses'},
        ),
        migrations.AlterModelOptions(
            name='verbs',
            options={'verbose_name_plural': 'Verbs'},
        ),
        migrations.AlterField(
            model_name='verbs',
            name='value',
            field=models.CharField(help_text='Fixed parameter value that is required for library.', max_length=50),
        ),
    ]
