# Generated by Django 4.2.1 on 2023-08-11 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_subjects_options_alter_tenses_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tense', models.CharField(help_text='Tense selected.', max_length=50)),
                ('subject', models.CharField(help_text='Subject selected.', max_length=50)),
                ('verb', models.CharField(help_text='Verb selected.', max_length=50)),
                ('correctAnswer', models.CharField(help_text='Correct answer.', max_length=50)),
                ('answer', models.CharField(help_text='Your answer.', max_length=50)),
                ('isCorrect', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
