# Generated by Django 4.1 on 2023-09-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='value',
            field=models.CharField(help_text='Fixed parameter value that is required for library.', max_length=50),
        ),
    ]
