# Generated by Django 4.2.1 on 2023-08-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='tense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenses'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.verbs'),
        ),
    ]
