# Generated by Django 4.1 on 2023-11-13 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_subjects_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irregularVerbs', models.ManyToManyField(related_name='irregular_preset', to='api.verbs')),
                ('regularVerbs', models.ManyToManyField(related_name='regular_preset', to='api.verbs')),
                ('tenses', models.ManyToManyField(to='api.tenses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
