# Generated by Django 4.1 on 2023-11-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_custompreset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompreset',
            name='name',
            field=models.CharField(blank=True, help_text='Preset name.', max_length=50, null=True),
        ),
    ]
