# Generated by Django 4.2.1 on 2023-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tenses_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenses',
            name='points',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
