# Generated by Django 4.2.1 on 2023-08-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tenses_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'Logs'},
        ),
    ]
