# Generated by Django 4.1 on 2023-11-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_custompreset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompreset',
            name='irregularVerbs',
            field=models.ManyToManyField(blank=True, null=True, related_name='irregular_preset', to='api.verbs'),
        ),
        migrations.AlterField(
            model_name='custompreset',
            name='regularVerbs',
            field=models.ManyToManyField(blank=True, null=True, related_name='regular_preset', to='api.verbs'),
        ),
        migrations.AlterField(
            model_name='custompreset',
            name='tenses',
            field=models.ManyToManyField(blank=True, null=True, to='api.tenses'),
        ),
    ]
