TENSES = [
    {"label": "Present", "value": "PRESENT"},
    {"label": "Futur", "value": "FUTUR"},
    {"label": "Imparfait", "value": "IMPARFAIT"},
    {"label": "Passe Simple", "value": "PASSE_SIMPLE"},
    {"label": "Conditionnel Present", "value": "CONDITIONNEL_PRESENT"},
    {"label": "Imperatif Present", "value": "IMPERATIF_PRESENT"},
    {"label": "Subjonctif Present", "value": "SUBJONCTIF_PRESENT"},
    {"label": "Subjonctif Imparfait", "value": "SUBJONCTIF_IMPARFAIT"},
    {"label": "Passe Compose", "value": "PASSE_COMPOSE"},
    {"label": "Plus Que Parfait", "value": "PLUS_QUE_PARFAIT"},
]

SUBJECTS = [
    {"label": "je", "value": 0},
    {"label": "tu", "value": 1},
    {"label": "il", "value": 2},
    {"label": "elle", "value": 2},
    {"label": "nous", "value": 3},
    {"label": "vous", "value": 4},
    {"label": "ils", "value": 5},
    {"label": "elles", "value": 5},
]

IRREGULAR_VERBS = [
    {"value": "acquérir", "isRegular": False},
    {"value": "aller", "isRegular": False},
    {"value": "assaillir", "isRegular": False},
    {"value": "s'asseoir", "isRegular": False},
    {"value": "apercevoir", "isRegular": False},
    {"value": "avoir", "isRegular": False},
    {"value": "appeler", "isRegular": False},
    {"value": "atteindre", "isRegular": False},
    {"value": "battre", "isRegular": False},
    {"value": "boire", "isRegular": False},
    {"value": "bouillir", "isRegular": False},
    {"value": "conclure", "isRegular": False},
    {"value": "commencer", "isRegular": False},
    {"value": "conduire", "isRegular": False},
    {"value": "connaître", "isRegular": False},
    {"value": "coudre", "isRegular": False},
    {"value": "courir", "isRegular": False},
    {"value": "couvrir", "isRegular": False},
    {"value": "craindre", "isRegular": False},
    {"value": "croire", "isRegular": False},
    {"value": "croître", "isRegular": False},
    {"value": "cueillir", "isRegular": False},
    {"value": "cuire", "isRegular": False},
    {"value": "devoir", "isRegular": False},
    {"value": "dire", "isRegular": False},
    {"value": "dissoudre", "isRegular": False},
    {"value": "dormir", "isRegular": False},
    {"value": "écrire", "isRegular": False},
    {"value": "envoyer", "isRegular": False},
    {"value": "employer", "isRegular": False},
    {"value": "faire", "isRegular": False},
    {"value": "falloir", "isRegular": False},
    {"value": "fuir", "isRegular": False},
    {"value": "geler", "isRegular": False},
    {"value": "haïr", "isRegular": False},
    {"value": "harceler", "isRegular": False},
    {"value": "jeter", "isRegular": False},
    {"value": "joindre", "isRegular": False},
    {"value": "lever", "isRegular": False},
    {"value": "lire", "isRegular": False},
    {"value": "manger", "isRegular": False},
    {"value": "mettre", "isRegular": False},
    {"value": "moudre", "isRegular": False},
    {"value": "mourir", "isRegular": False},
    {"value": "mouvoir", "isRegular": False},
    {"value": "naître", "isRegular": False},
    {"value": "nettoyer", "isRegular": False},
    {"value": "nuire", "isRegular": False},
    {"value": "ouvrir", "isRegular": False},
    {"value": "payer", "isRegular": False},
    {"value": "plaindre", "isRegular": False},
    {"value": "plaire", "isRegular": False},
    {"value": "partir", "isRegular": False},
    {"value": "peser", "isRegular": False},
    {"value": "placer", "isRegular": False},
    {"value": "pleuvoir", "isRegular": False},
    {"value": "pouvoir", "isRegular": False},
    {"value": "prendre", "isRegular": False},
    {"value": "préférer", "isRegular": False},
    {"value": "résoudre", "isRegular": False},
    {"value": "rire", "isRegular": False},
    {"value": "rompre", "isRegular": False},
    {"value": "savoir", "isRegular": False},
    {"value": "sentir", "isRegular": False},
    {"value": "servir", "isRegular": False},
    {"value": "sortir", "isRegular": False},
    {"value": "suffire", "isRegular": False},
    {"value": "suivre", "isRegular": False},
    {"value": "se taire", "isRegular": False},
    {"value": "tenir", "isRegular": False},
    {"value": "traire", "isRegular": False},
    {"value": "vaincre", "isRegular": False},
    {"value": "valoir", "isRegular": False},
    {"value": "venir", "isRegular": False},
    {"value": "vêtir", "isRegular": False},
    {"value": "vivre", "isRegular": False},
    {"value": "voir", "isRegular": False},
    {"value": "vouloir", "isRegular": False},
]


REGULAR_VERBS = [
    {"value": "agir", "isRegular": True},
    {"value": "aimer", "isRegular": True},
    {"value": "appliquer", "isRegular": True},
    {"value": "arrêter", "isRegular": True},
    {"value": "arriver", "isRegular": True},
    {"value": "attaquer", "isRegular": True},
    {"value": "attendre", "isRegular": True},
    {"value": "avertir", "isRegular": True},
    {"value": "chercher", "isRegular": True},
    {"value": "choisir", "isRegular": True},
    {"value": "commencer", "isRegular": True},
    {"value": "conseiller", "isRegular": True},
    {"value": "continuer", "isRegular": True},
    {"value": "correspondre", "isRegular": True},
    {"value": "coûter", "isRegular": True},
    {"value": "crier", "isRegular": True},
    {"value": "demander", "isRegular": True},
    {"value": "descendre", "isRegular": True},
    {"value": "donner", "isRegular": True},
    {"value": "entendre", "isRegular": True},
    {"value": "entrer", "isRegular": True},
    {"value": "exister", "isRegular": True},
    {"value": "expliquer", "isRegular": True},
    {"value": "fermer", "isRegular": True},
    {"value": "finir", "isRegular": True},
    {"value": "habiter", "isRegular": True},
    {"value": "manger", "isRegular": True},
    {"value": "manquer", "isRegular": True},
    {"value": "mener", "isRegular": True},
    {"value": "monter", "isRegular": True},
    {"value": "nager", "isRegular": True},
    {"value": "parler", "isRegular": True},
    {"value": "passer", "isRegular": True},
    {"value": "penser", "isRegular": True},
    {"value": "perdre", "isRegular": True},
    {"value": "porter", "isRegular": True},
    {"value": "produire", "isRegular": True},
    {"value": "punir", "isRegular": True},
    {"value": "raconter", "isRegular": True},
    {"value": "réfléchir", "isRegular": True},
    {"value": "regarder", "isRegular": True},
    {"value": "remplir", "isRegular": True},
    {"value": "rencontrer", "isRegular": True},
    {"value": "rendre", "isRegular": True},
    {"value": "rentrer", "isRegular": True},
    {"value": "répondre", "isRegular": True},
    {"value": "rester", "isRegular": True},
    {"value": "retourner", "isRegular": True},
    {"value": "réussir", "isRegular": True},
    {"value": "rouler", "isRegular": True},
    {"value": "se coucher", "isRegular": True},
    {"value": "se laver", "isRegular": True},
    {"value": "se promener", "isRegular": True},
    {"value": "se tromper", "isRegular": True},
    {"value": "sembler", "isRegular": True},
    {"value": "tomber", "isRegular": True},
    {"value": "toucher", "isRegular": True},
    {"value": "trouver", "isRegular": True},
    {"value": "vendre", "isRegular": True},
    {"value": "voler", "isRegular": True},
]


VERBS = [*REGULAR_VERBS, *IRREGULAR_VERBS]
